# Project information
site_name: Calypso
site_url: https://mauricekuenicke.github.io/calypso/
site_author: Maurice Künicke
edit_uri: edit/main/docs/

# Repository
repo_name: MauriceKuenicke/calypso
repo_url: https://github.com/MauriceKuenicke/calypso


# Configuration
theme:
  name: material
  logo: 'assets/logo/svg/Black logo - no background.svg'

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  font:
    text: Outfit
    code: Outfit Mono

  features:
    - navigation.tracking 
    - navigation.tabs.sticky
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.highlight
    - search.share
    - announce.dismiss
    - navigation.footer
    - content.action.edit
    #- content.action.view
    - content.code.copy
    - content.code.annotate

# Customization
extra:
  social:
      - icon: fontawesome/brands/github
        link: https://github.com/MauriceKuenicke

# Page Tree
nav:
  - Home: index.md
  - Setup: setup/documentation.md
  - Calypso CLI: cli/index.md
  - Contribute: 
      - Dev-Environment: development/environment.md
      - Pre-Commit Hooks: development/pre-commit-hooks.md

# Plugins
plugins:
  - search
  - tags

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - footnotes
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
